; Container 4GB RAM, 4 vCPU
pm = dynamic
pm.max_children = 30       ; Max limit based on RAM
pm.start_servers = 10      ; Initialize 10 workers on start
pm.min_spare_servers = 10  ; Always keep at least 10 idle workers waiting for requests
pm.max_spare_servers = 20  ; Do not keep more than 20 idle workers (to save RAM for other tasks)
pm.max_requests = 500      ; Important: Automatically reset process after 500 requests to prevent RAM leaks
request_terminate_timeout = 600s