###########################
# Stage 1: Build
###########################
FROM php:8.2-fpm-alpine AS builder

RUN apk add --no-cache \
    freetype-dev libjpeg-turbo-dev libpng-dev libxml2-dev libzip-dev \
    icu-dev oniguruma-dev openldap-dev krb5-dev curl-dev openssl-dev \
    unzip g++ make autoconf

RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) \
        gd pdo_mysql mbstring xml zip curl intl ldap mysqli soap opcache bcmath \
    && pecl install apcu && docker-php-ext-enable apcu

WORKDIR /tmp/build

COPY .docker/custom_packages/ ./custom_packages
COPY .docker/scripts ./docker/scripts

COPY SuiteCRM-8.9.2.zip .
RUN unzip -q SuiteCRM-8.9.2.zip -d SuiteCRM \
    && rm SuiteCRM-8.9.2.zip

COPY .docker/custom_fixes/ SuiteCRM/

RUN cp -rn custom_packages/Extension/* SuiteCRM/public/legacy/custom/Extension/ \
    && cp -rn custom_packages/include/* SuiteCRM/public/legacy/custom/include/

RUN rm -rf custom_packages \
    && find SuiteCRM -type d -exec chmod 2755 {} \; \
    && find SuiteCRM -type f -exec chmod 0644 {} \;

###########################
# Stage 2: Production
###########################
FROM php:8.2-fpm-alpine

# Install Runtime libraries (no use -dev)
RUN apk add --no-cache \
    bash \
    nginx libpng libjpeg-turbo freetype libxml2 libzip icu-libs \
    oniguruma openldap-clients krb5-libs curl openssl \
    && mkdir -p /run/nginx

WORKDIR /var/www/html/

# Copy PHP extensions & config from builder
COPY --from=builder /usr/local/lib/php/extensions /usr/local/lib/php/extensions
COPY --from=builder /usr/local/etc/php/conf.d /usr/local/etc/php/conf.d

# !Important: Copy code and set owner www-data (1 Layer for Source)
COPY --from=builder --chown=www-data:www-data /tmp/build/ /var/www/html/

# System configuration
COPY .docker/php/suitecrm.ini $PHP_INI_DIR/conf.d/suitecrm-custom.ini
COPY .docker/nginx/full-stack.conf /etc/nginx/http.d/default.conf
COPY .docker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
COPY .docker/entrypoint-utils.sh /usr/local/bin/entrypoint-utils.sh

# Comment out this if you're running in local dev and want to mount code
RUN chmod +x /usr/local/bin/docker-entrypoint.sh && chmod +x SuiteCRM/bin/console

# Uncomment this if you're running in local dev and want to mount code to /var/www/html/SuiteCRM 
# This is for debugging and adding Vardefs
# COPY docker/local-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
# RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 80
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["php-fpm"]