upstream php_workers {
    # Kubernetes ClusterIP Service (load balance to multi Pod PHP)
    server suitecrm_worker:9000;

    # Keep connections open to reduce TCP + FastCGI handshake overhead
    keepalive 100;
}

upstream web_app {
    server suitecrm_web:80;
}

server {
    listen 80;
    listen [::]:80;
    server_name dev-epos-crm.360f.com;
    return 301 https://$host$request_uri;
}

http {
    access_log /dev/stdout;
    error_log  /dev/stderr;
}

server {	
	listen 443 ssl;
    listen [::]:443 ssl;
    server_name dev-epos-crm.360f.com;

    ssl_certificate /etc/nginx/ssl/dev-epos-crm.360f.com.crt;
    ssl_certificate_key /etc/nginx/ssl/dev-epos-crm.360f.com.key;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Route to api_gateway
    location ~ ^/Api/ {
        include fastcgi_params;
        fastcgi_pass php_workers;

        # Reuse connection to upstream (important for high RPS)
        fastcgi_keep_conn on;

        # Force all requests to go through front controller
        fastcgi_param SCRIPT_FILENAME /var/www/html/SuiteCRM/public/index.php;

        # Preserve original request URI (important for Symfony routing)
        fastcgi_param REQUEST_URI $request_uri;

        # Buffer tuning (for JSON APIs)
        fastcgi_buffer_size 128k;
        fastcgi_buffers 8 256k;
        fastcgi_busy_buffers_size 256k;

        # Timeouts (tuned for high load)
        fastcgi_connect_timeout 5s;   # connect to PHP
        fastcgi_send_timeout 30s;     # send request
        fastcgi_read_timeout 60s;     # wait response

        # Security headers (basic hardening)
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options DENY;
        add_header X-XSS-Protection "1; mode=block";
    }

    # Route to web
    location / {
        proxy_pass http://web_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}